### ISSUE TITLE
Replace style with class in <td> for NaN values

### ISSUE THREAD

**Issue by jaromir-benes** [OGResearch/rephrase#2]
Replace the hard-coded style attribute in TDs containing a NaN value
`<td class="rephrase-data-table-cell" style="text-align: right;">` 
with a class based indicator of a NaN value, e.g.
`<td class="rephrase-data-table-cell rephrase-data-nan">`

**Comment by nul0m** [comment]
Fixed in c2d40e5. New class name is `rephrase-table-data-nan`
